version: 0.2

phases:
  install:
    commands:
      #- rm package-lock.json
      - npm install --silent --progress=false -g npm
      
      ## Dependencies
      - npm install --silent --progress-false
      - npm --version
      - npm install --silent --progress=false -g serverless
      - npm install --silent --save–dev serverless-stack-output
      
  build:
    commands:
      - mkdir artifacts
      - mkdir artifacts/dev
      - serverless package --package artifacts/dev --stage dev -v

artifacts:
 files:
   - artifacts/**/*
   - serverless.yml
   - deploy.sh
   - package.json
   - package-lock.json