version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      - python -m unittest discover .
  build:
    commands:
      - mkdir artifacts
      - mkdir artifacts/dev
      - serverless package --package artifacts/dev --stage dev -v      
      
artifacts:
 files:
   - artifacts/**/*
   - serverless.yml
   - deploy.sh
   - package.json
   - package-lock.json      